### PR TITLE
make independent by implementing curryN

### PR DESCRIPTION
**Pull request by natemc**
Let me know if you require further edits.  Thanks!

### CODE REVIEW

**Comment by NodeGuy** [comment]
Actually hold off on that; I've decided to replace Ramda with [a smaller library](https://github.com/fp-js/fj-curry) instead of writing curry ourselves.

**Comment by NodeGuy** [comment]
Done in https://github.com/NodeGuy/generic/commit/560e426b472164356286224941e4eabb3ba48112.

**Comment by natemc** [comment]
OK.  I have a few questions:

In contrast to Rambda's curry (and the version I wrote), the curry in the new library you've chosen does not set the length of the curried function correctly.  Is that what you want?

If not, I'm happy to make the fixes you requested.  That said, curryN is private, and the existing tests pass and exercise curryN fully.  What tests do you feel are missing?  Do you want to make curryN public or is there a trick I should learn for testing private methods directly?

Sorry about the style error; I tried to copy what you were doing, and I missed the const.  I've since installed standard, so it shouldn't happen again.

**Comment by NodeGuy** [comment]
I would like the length to be set correctly.  I've created an issue for this, please see #2.

If we were to write curry ourselves then I would want more comprehensive tests [like those in fj-curry](https://github.com/fp-js/fj-curry/blob/master/test.es6) and one to test the `length` property.  Part of my motivation for using a separate library is that I don't want to make `curryN` public here.

**Pull request closed without merging**
